# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a2993c599c6f9e091f1ed40af09f4bc333a64e3963c906a39562c0084f310e427915c008c16cc05ace66255890ab239520e531b574ee3a236892e12cfe45f47

test:
  secret_key_base: 44da8ec0daf0fc2925d349ed7e4f5f7d8e1601bb68c65aade50481ef9082c7aeff0d7547405c481412e45bba1b6b6814682a4b8c2764694c16d19ff5e72d7547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
